services:

  postgres:
    image: postgres:17-alpine
    container_name: nik_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nik_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: nik185/nik-backend:latest
    container_name: nik_backend
    restart: unless-stopped
    ports:
      - "5055:5055"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS:        http://+:5055
      ConnectionStrings__Postgres: >-
        Server=postgres;Port=5432;Database=${POSTGRES_DB};
        Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
        Pooling=true;MinPoolSize=0;MaxPoolSize=100;Timeout=15;
      Jwt__SecretKey:                    ${JWT_SECRET_KEY}
      Jwt__Issuer:                       ${JWT_ISSUER}
      Jwt__Audience:                     ${JWT_AUDIENCE}
      Jwt__AccessTokenExpirationMinutes: ${JWT_ACCESS_EXPIRY_MINUTES}
      Jwt__RefreshTokenExpirationDays:   ${JWT_REFRESH_EXPIRY_DAYS}
      CORS_ORIGINS:                      ${CORS_ORIGINS}
      Cloudinary__UrlUpload:             ${CLOUDINARY_URL_UPLOAD}
      Cloudinary__CloudName:             ${CLOUDINARY_CLOUD_NAME}
      Cloudinary__ApiKey:                ${CLOUDINARY_API_KEY}
      Cloudinary__ApiSecret:             ${CLOUDINARY_API_SECRET}
      Cloudinary__UploadFolder:          ${CLOUDINARY_UPLOAD_FOLDER}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nik_net

  frontend:
    image: nik185/nik-frontend:latest
    container_name: nik_frontend
    restart: unless-stopped
    ports:
      - "3000:4000"
    environment:
      PORT: 4000
      BACKEND_URL: "http://backend:5055"
    depends_on:
      - backend
    networks:
      - nik_net

volumes:
  postgres_data:

networks:
  nik_net:
    driver: bridge
