export enum ApplicationMessage {
  FILE_NOT_EXITS = "file.not.exists",
  FILE_TYPE_APPLY = "file.type.apply",
  FILE_MAX_SIZE = "file.max.size",
  LOADING_PROCESS = "loading.process",
}

export enum ApplicationTitle {
  CATEGORY              = 'category',
  ARCHIVES              = 'archives',
  HAVE_A_QUESTIONS      = 'have-questions?',
  WRITE_BY              = "write-by",
  CONTINUE_READING      = "continuing-reading",
  NEWS_LETTER_TITLE     = "news-letter.title",
  NEW_LETTER_CONTENT    = "news-letter.content",
  EMAIL_ADDRESS         = "email-address",
  SUBSCRIBE             = "subscribe",
  CONTACT_INFORMATION   = "contact-information",
  ADDRESS               = "address",
  PHONE                 = "phone",
  EMAIL                 = "email",
  WEBSITE               = "website",
  YOUR_NAME             = "your-name",
  YOUR_EMAIL            = "your-email",
  SUBJECT               = "subject",
  MESSAGE               = "message",
  SEND_MESSAGE          = "send-message",
  HELLO_I_AM            = "hello-i-am",
  MORE_ABOUT_ME         = "more-about-me",
  ARTICLES              = "articles",
  ARTICLE_DESCRIPTION   = "articles-description",
  DESCRIPTION_SEARCH_BOX= "description-search-box",
  POPULAR_ARTICLES      = "popular-articles",
  TAG_CLOUD             = "tag-cloud",
  OUR_STORY             = "our-story",
  PHOTO                 = "photo",
  BACK                  = "back",
  PHOTOGRAPHY           = "photography",
  ALBUM_COUNT           = "photography.album-count",
  ALBUM_SUB_COUNT       = "photography.album-sub-count",
  ALBUM_EMPTY           = "photography.album-empty",
  COMMENT               = "comment",
  REPLY                 = "reply",
  LEAVE_COMMENT         = "leave-a-comment",
  POST_COMMENT          = "post-comment",
  CONTACT_SEND_SUCCESS  = "contact.send-success",
  CONTACT_SEND_ERROR    = "contact.send-error",
}

export enum AdminMessage {
  // ─── Shared ──────────────────────────────────────────────────────────────
  SAVE              = 'admin.save',
  SAVING            = 'admin.saving',
  CANCEL            = 'admin.cancel',
  ERROR_GENERIC        = 'admin.error.generic',
  TOAST_DELETE_SUCCESS = 'admin.toast.delete-success',
  TOAST_DELETE_ERROR   = 'admin.toast.delete-error',
  TOAST_SAVE_SUCCESS   = 'admin.toast.save-success',
  TOAST_SAVE_ERROR     = 'admin.toast.save-error',
  LOADING           = 'admin.loading',
  LABEL_NAME          = 'admin.label.name',
  LABEL_TITLE         = 'admin.label.title',
  LABEL_DESCRIPTION   = 'admin.label.description',
  LABEL_IMAGE         = 'admin.label.image',
  LABEL_ORDER         = 'admin.label.order',
  LABEL_KEY           = 'admin.label.key',
  LABEL_VALUE         = 'admin.label.value',
  LABEL_LANGUAGE      = 'admin.label.language',
  LABEL_SLUG          = 'admin.label.slug',
  LABEL_VIEWS         = 'admin.label.views',
  LABEL_LIKE          = 'admin.label.like',
  LABEL_COMMENT_COUNT = 'admin.label.comment-count',
  LABEL_CREATED_DATE  = 'admin.label.created-date',
  LABEL_IMAGE_COUNT   = 'admin.label.image-count',
  LABEL_ARTICLE_COUNT = 'admin.label.article-count',
  LABEL_CONTENT       = 'admin.label.content',
  LABEL_ARTICLE_ID    = 'admin.label.article-id',
  LABEL_AUTHOR        = 'admin.label.author',
  LABEL_REPLY_ID      = 'admin.label.reply-id',
  LABEL_LANG_CODE     = 'admin.label.lang-code',
  LABEL_USERNAME      = 'admin.label.username',
  LABEL_EMAIL         = 'admin.label.email',
  LABEL_PHONE         = 'admin.label.phone',
  LABEL_BIO           = 'admin.label.bio',

  // ─── Dashboard ───────────────────────────────────────────────────────────
  DASHBOARD_TITLE         = 'admin.dashboard.title',
  DASHBOARD_SUBTITLE      = 'admin.dashboard.subtitle',
  DASHBOARD_QUICK         = 'admin.dashboard.quick',
  DASHBOARD_NEW_ARTICLE   = 'admin.dashboard.new-article',
  DASHBOARD_NEW_ALBUM     = 'admin.dashboard.new-album',
  DASHBOARD_NEW_CATEGORY  = 'admin.dashboard.new-category',
  DASHBOARD_NEW_TAG       = 'admin.dashboard.new-tag',
  DASHBOARD_SETTINGS      = 'admin.dashboard.settings',
  DASHBOARD_STAT_ARTICLES   = 'admin.dashboard.stat.articles',
  DASHBOARD_STAT_ALBUMS     = 'admin.dashboard.stat.albums',
  DASHBOARD_STAT_CATEGORIES = 'admin.dashboard.stat.categories',
  DASHBOARD_STAT_TAGS       = 'admin.dashboard.stat.tags',
  DASHBOARD_STAT_FILES      = 'admin.dashboard.stat.files',
  DASHBOARD_STAT_USERS      = 'admin.dashboard.stat.users',

  // ─── Articles ─────────────────────────────────────────────────────────────
  ARTICLES_PAGE_TITLE    = 'admin.articles.title',
  ARTICLES_CREATE_BTN    = 'admin.articles.create',
  ARTICLES_MODAL_CREATE  = 'admin.articles.modal.create',
  ARTICLES_MODAL_EDIT    = 'admin.articles.modal.edit',
  ARTICLES_FORM_TITLE    = 'admin.articles.form.title',
  ARTICLES_FORM_DESC     = 'admin.articles.form.desc',
  ARTICLES_FORM_CONTENT  = 'admin.articles.form.content',
  ARTICLES_FORM_COVER    = 'admin.articles.form.cover',
  ARTICLES_FORM_CATEGORIES = 'admin.articles.form.categories',
  ARTICLES_FORM_TAGS     = 'admin.articles.form.tags',
  ARTICLES_SAVE          = 'admin.articles.save',

  // ─── Albums ───────────────────────────────────────────────────────────────
  ALBUMS_PAGE_TITLE     = 'admin.albums.title',
  ALBUMS_SUBTITLE       = 'admin.albums.subtitle',
  ALBUMS_CREATE_BTN     = 'admin.albums.create',
  ALBUMS_MODAL_CREATE   = 'admin.albums.modal.create',
  ALBUMS_MODAL_EDIT     = 'admin.albums.modal.edit',
  ALBUMS_FORM_PARENT    = 'admin.albums.form.parent',
  ALBUMS_FORM_NO_PARENT = 'admin.albums.form.no-parent',
  ALBUMS_VIEW_LIST      = 'admin.albums.view.list',
  ALBUMS_VIEW_TREE      = 'admin.albums.view.tree',
  ALBUMS_VIEW_EXPLORER  = 'admin.albums.view.explorer',
  ALBUMS_EMPTY_CHILDREN = 'admin.albums.empty-children',
  ALBUMS_FILES_TITLE    = 'admin.albums.files.title',
  ALBUMS_FILES_EMPTY    = 'admin.albums.files.empty',
  ALBUMS_FILES_ADD      = 'admin.albums.files.add',
  ALBUMS_FILES_REMOVE   = 'admin.albums.files.remove',
  ALBUMS_ROOT           = 'admin.albums.root',
  ALBUMS_EXPAND_ALL     = 'admin.albums.expand-all',
  ALBUMS_COLLAPSE_ALL   = 'admin.albums.collapse-all',
  ALBUMS_COPY_URL       = 'admin.albums.copy-url',
  ALBUMS_SET_COVER      = 'admin.albums.set-cover',
  ALBUMS_IS_COVER       = 'admin.albums.is-cover',
  ALBUMS_COVER_FOR      = 'admin.albums.cover-for',
  ALBUMS_COUNT_SUFFIX   = 'admin.albums.count-suffix',

  // ─── Tags ─────────────────────────────────────────────────────────────────
  TAGS_PAGE_TITLE   = 'admin.tags.title',
  TAGS_SUBTITLE     = 'admin.tags.subtitle',
  TAGS_CREATE_BTN   = 'admin.tags.create',
  TAGS_MODAL_CREATE = 'admin.tags.modal.create',
  TAGS_MODAL_EDIT   = 'admin.tags.modal.edit',

  // ─── Categories ───────────────────────────────────────────────────────────
  CATEGORIES_PAGE_TITLE   = 'admin.categories.title',
  CATEGORIES_SUBTITLE     = 'admin.categories.subtitle',
  CATEGORIES_CREATE_BTN   = 'admin.categories.create',
  CATEGORIES_MODAL_CREATE = 'admin.categories.modal.create',
  CATEGORIES_MODAL_EDIT   = 'admin.categories.modal.edit',

  // ─── Users ────────────────────────────────────────────────────────────────
  USERS_PAGE_TITLE    = 'admin.users.title',
  USERS_SUBTITLE      = 'admin.users.subtitle',
  USERS_MODAL_EDIT    = 'admin.users.modal.edit',
  USERS_FORM_USERNAME = 'admin.users.form.username',
  USERS_FORM_EMAIL    = 'admin.users.form.email',
  USERS_FORM_PHONE    = 'admin.users.form.phone',
  USERS_FORM_BIO      = 'admin.users.form.bio',

  // ─── Languages ────────────────────────────────────────────────────────────
  LANGUAGES_PAGE_TITLE   = 'admin.languages.title',
  LANGUAGES_SUBTITLE     = 'admin.languages.subtitle',
  LANGUAGES_CREATE_BTN   = 'admin.languages.create',
  LANGUAGES_MODAL_CREATE = 'admin.languages.modal.create',
  LANGUAGES_MODAL_EDIT   = 'admin.languages.modal.edit',
  LANGUAGES_FORM_CODE    = 'admin.languages.form.code',

  // ─── Comments ─────────────────────────────────────────────────────────────
  COMMENTS_PAGE_TITLE          = 'admin.comments.title',
  COMMENTS_SUBTITLE            = 'admin.comments.subtitle',
  COMMENTS_SEARCH_PLACEHOLDER  = 'admin.comments.search-placeholder',
  COMMENTS_SEARCH_BTN          = 'admin.comments.search',

  // ─── Translations ─────────────────────────────────────────────────────────
  TRANSLATIONS_ALL_LANGS       = 'admin.translations.all-langs',
  TRANSLATIONS_PAGE_TITLE      = 'admin.translations.title',
  TRANSLATIONS_SUBTITLE        = 'admin.translations.subtitle',
  TRANSLATIONS_ADD_KEY_BTN     = 'admin.translations.add-key',
  TRANSLATIONS_CREATE_BTN      = 'admin.translations.create',
  TRANSLATIONS_MODAL_CREATE    = 'admin.translations.modal.create',
  TRANSLATIONS_MODAL_EDIT      = 'admin.translations.modal.edit',
  TRANSLATIONS_MODAL_KEY_TITLE = 'admin.translations.modal.key-title',
  TRANSLATIONS_FORM_VALUE      = 'admin.translations.form.value',
  TRANSLATIONS_FORM_CHOOSE_KEY  = 'admin.translations.form.choose-key',
  TRANSLATIONS_FORM_CHOOSE_LANG = 'admin.translations.form.choose-lang',
  TRANSLATIONS_SAVE_KEY        = 'admin.translations.save-key',

  // ─── Sys Config ───────────────────────────────────────────────────────────
  SYSCONFIG_PAGE_TITLE       = 'admin.sys-config.title',
  SYSCONFIG_SUBTITLE         = 'admin.sys-config.subtitle',
  SYSCONFIG_CREATE_BTN       = 'admin.sys-config.create',
  SYSCONFIG_MODAL_CREATE     = 'admin.sys-config.modal.create',
  SYSCONFIG_MODAL_EDIT       = 'admin.sys-config.modal.edit',
  SYSCONFIG_FORM_VALUE_LABEL = 'admin.sys-config.form.value-label',
  SYSCONFIG_FORM_HINT        = 'admin.sys-config.form.hint',
  SYSCONFIG_EDITOR_BACK      = 'admin.sys-config.editor.back',
  SYSCONFIG_FORM_VI          = 'admin.sys-config.form.vi',
  SYSCONFIG_FORM_EN          = 'admin.sys-config.form.en',
  SYSCONFIG_INFO_NAME        = 'admin.sys-config.info.name',
  SYSCONFIG_INFO_EMAIL       = 'admin.sys-config.info.email',
  SYSCONFIG_INFO_PHONE       = 'admin.sys-config.info.phone',
  SYSCONFIG_INFO_ADDRESS     = 'admin.sys-config.info.address',
  SYSCONFIG_INFO_WEBSITE     = 'admin.sys-config.info.website',
  SYSCONFIG_INFO_AVATAR      = 'admin.sys-config.info.avatar',
  SYSCONFIG_INFO_BIO         = 'admin.sys-config.info.bio',
  SYSCONFIG_INFO_INTRO       = 'admin.sys-config.info.intro',
  SYSCONFIG_SOCIAL_URL       = 'admin.sys-config.social.url',
  SYSCONFIG_NAV_KEY          = 'admin.sys-config.nav.key',
  SYSCONFIG_NAV_ROUTE        = 'admin.sys-config.nav.route',
  SYSCONFIG_ADD_ITEM         = 'admin.sys-config.add-item',

  // ─── Files ────────────────────────────────────────────────────────────────
  FILES_PAGE_TITLE      = 'admin.files.title',
  FILES_CREATE_BTN      = 'admin.files.create',
  FILES_MODAL_CREATE    = 'admin.files.modal.create',
  FILES_MODAL_EDIT      = 'admin.files.modal.edit',
  FILES_FORM_MEDIA      = 'admin.files.form.media',
  FILES_EMPTY           = 'admin.files.empty',
  FILES_DROP_HINT       = 'admin.files.drop',
  FILES_BATCH_UPLOADING = 'admin.files.batch',
  FILES_UPLOAD_REQUIRED = 'admin.files.upload-required',
  FILES_SAVE_FAILED     = 'admin.files.save-failed',

  // ─── Contacts ─────────────────────────────────────────────────────────────
  CONTACTS_PAGE_TITLE   = 'admin.contacts.title',
  CONTACTS_SUBTITLE     = 'admin.contacts.subtitle',
  CONTACTS_LABEL_NAME   = 'admin.contacts.label.name',
  CONTACTS_LABEL_EMAIL  = 'admin.contacts.label.email',
  CONTACTS_LABEL_SUBJECT= 'admin.contacts.label.subject',
  CONTACTS_LABEL_MESSAGE= 'admin.contacts.label.message',
  CONTACTS_LABEL_STATUS = 'admin.contacts.label.status',
  CONTACTS_STATUS_READ  = 'admin.contacts.status.read',
  CONTACTS_STATUS_UNREAD= 'admin.contacts.status.unread',
  CONTACTS_MARK_READ    = 'admin.contacts.mark-read',
  CONTACTS_DETAIL_TITLE = 'admin.contacts.detail.title',
  CONTACTS_CLOSE        = 'admin.contacts.close',

  // ─── Content Translations ─────────────────────────────────────────────────
  CONTENT_TRANS_TITLE         = 'admin.content-trans.title',
  CONTENT_TRANS_SUBTITLE      = 'admin.content-trans.subtitle',
  CONTENT_TRANS_ENTITY_TYPE   = 'admin.content-trans.entity-type',
  CONTENT_TRANS_LANG          = 'admin.content-trans.lang',
  CONTENT_TRANS_STATUS_ALL    = 'admin.content-trans.status.all',
  CONTENT_TRANS_STATUS_DONE   = 'admin.content-trans.status.done',
  CONTENT_TRANS_STATUS_TODO   = 'admin.content-trans.status.todo',
  CONTENT_TRANS_TRANSLATE_BTN = 'admin.content-trans.translate-btn',
  CONTENT_TRANS_MODAL_TITLE   = 'admin.content-trans.modal.title',
  CONTENT_TRANS_SAVE          = 'admin.content-trans.save',
  CONTENT_TRANS_SAVING        = 'admin.content-trans.saving',
  CONTENT_TRANS_STATUS_LABEL  = 'admin.content-trans.status',
  CONTENT_TRANS_ORIGINAL      = 'admin.content-trans.original',
  CONTENT_TRANS_TRANSLATION   = 'admin.content-trans.translation',
  CONTENT_TRANS_BACK          = 'admin.content-trans.back',

  // ─── Sidebar ──────────────────────────────────────────────────────────────
  SIDEBAR_HOME              = 'admin.sidebar.home',
  SIDEBAR_LOGOUT            = 'admin.sidebar.logout',
  SIDEBAR_GROUP_OVERVIEW    = 'admin.sidebar.group.overview',
  SIDEBAR_GROUP_CONTENT     = 'admin.sidebar.group.content',
  SIDEBAR_GROUP_COMMUNITY   = 'admin.sidebar.group.community',
  SIDEBAR_GROUP_I18N        = 'admin.sidebar.group.i18n',
  SIDEBAR_GROUP_SYSTEM      = 'admin.sidebar.group.system',
  SIDEBAR_NAV_DASHBOARD     = 'admin.sidebar.nav.dashboard',
  SIDEBAR_NAV_ARTICLES      = 'admin.sidebar.nav.articles',
  SIDEBAR_NAV_ALBUMS        = 'admin.sidebar.nav.albums',
  SIDEBAR_NAV_CATEGORIES    = 'admin.sidebar.nav.categories',
  SIDEBAR_NAV_TAGS          = 'admin.sidebar.nav.tags',
  SIDEBAR_NAV_COMMENTS      = 'admin.sidebar.nav.comments',
  SIDEBAR_NAV_FILES         = 'admin.sidebar.nav.files',
  SIDEBAR_NAV_USERS         = 'admin.sidebar.nav.users',
  SIDEBAR_NAV_LANGUAGES     = 'admin.sidebar.nav.languages',
  SIDEBAR_NAV_TRANSLATIONS  = 'admin.sidebar.nav.translations',
  SIDEBAR_NAV_SETTINGS      = 'admin.sidebar.nav.settings',
  SIDEBAR_NAV_CONTACTS      = 'admin.sidebar.nav.contacts',
  SIDEBAR_NAV_PAGE_VIEWS    = 'admin.sidebar.nav.page-views',
  SIDEBAR_NAV_HERO_SLIDES   = 'admin.sidebar.nav.hero-slides',
  SIDEBAR_NAV_CONTENT_TRANS = 'admin.sidebar.nav.content-trans',

  // ─── Hero Slides ──────────────────────────────────────────────────────────
  HERO_SLIDES_TITLE         = 'admin.hero-slides.title',
  HERO_SLIDES_SUBTITLE      = 'admin.hero-slides.subtitle',
  HERO_SLIDES_CREATE        = 'admin.hero-slides.create',
  HERO_SLIDES_MODAL_CREATE  = 'admin.hero-slides.modal.create',
  HERO_SLIDES_MODAL_EDIT    = 'admin.hero-slides.modal.edit',
  HERO_SLIDES_LABEL_IMAGE   = 'admin.hero-slides.label.image',
  HERO_SLIDES_LABEL_TITLE   = 'admin.hero-slides.label.title',
  HERO_SLIDES_LABEL_DESC    = 'admin.hero-slides.label.desc',
  HERO_SLIDES_LABEL_ORDER   = 'admin.hero-slides.label.order',
  HERO_SLIDES_LABEL_ACTIVE  = 'admin.hero-slides.label.active',
  HERO_SLIDES_EMPTY         = 'admin.hero-slides.empty',

  // ─── Topbar ───────────────────────────────────────────────────────────────
  TOPBAR_NOTIFICATIONS     = 'admin.topbar.notifications',
  TOPBAR_NO_NOTIFICATIONS  = 'admin.topbar.no-notifications',
  TOPBAR_VIEW_ALL          = 'admin.topbar.view-all',

  // ─── Dashboard (extended) ─────────────────────────────────────────────────
  DASHBOARD_WELCOME        = 'admin.dashboard.welcome',
  DASHBOARD_SESSION_TITLE  = 'admin.dashboard.session.title',
  DASHBOARD_SESSION_BROWSER= 'admin.dashboard.session.browser',
  DASHBOARD_SESSION_TZ     = 'admin.dashboard.session.timezone',
  DASHBOARD_SESSION_LANG   = 'admin.dashboard.session.lang',
  DASHBOARD_RECENT_MSG     = 'admin.dashboard.recent-messages',
  DASHBOARD_NO_UNREAD      = 'admin.dashboard.no-unread',
  DASHBOARD_VIEW_ALL       = 'admin.dashboard.view-all',
  DASHBOARD_STAT_CONTACTS  = 'admin.dashboard.stat.contacts',

  // ─── Page Views ───────────────────────────────────────────────────────────
  PV_PAGE_TITLE     = 'admin.page-views.title',
  PV_SUBTITLE       = 'admin.page-views.subtitle',
  PV_EXPORT         = 'admin.page-views.export',
  PV_TAB_CHART      = 'admin.page-views.tab.chart',
  PV_TAB_TABLE      = 'admin.page-views.tab.table',
  PV_PERIOD_WEEK    = 'admin.page-views.period.week',
  PV_PERIOD_MONTH   = 'admin.page-views.period.month',
  PV_PERIOD_YEAR    = 'admin.page-views.period.year',
  PV_TOTAL_VIEWS    = 'admin.page-views.total-views',
  PV_UNIQUE_IPS     = 'admin.page-views.unique-ips',
  PV_AVG_DAY        = 'admin.page-views.avg-day',
  PV_TOP_PAGES      = 'admin.page-views.top-pages',
  PV_CHART_TITLE    = 'admin.page-views.chart-title',
  PV_NO_DATA        = 'admin.page-views.no-data',
  PV_LABEL_IP       = 'admin.page-views.label.ip',
  PV_LABEL_PATH     = 'admin.page-views.label.path',
  PV_LABEL_BROWSER  = 'admin.page-views.label.browser',
  PV_LABEL_OS       = 'admin.page-views.label.os',
  PV_LABEL_REFERER  = 'admin.page-views.label.referer',
  PV_BROWSER_CHART  = 'admin.page-views.browser-chart',
  PV_OS_CHART       = 'admin.page-views.os-chart',
  PV_HOURLY_CHART   = 'admin.page-views.hourly-chart',

  // ─── Login ────────────────────────────────────────────────────────────────
  LOGIN_TITLE               = 'admin.login.title',
  LOGIN_SUBTITLE            = 'admin.login.subtitle',
  LOGIN_EMAIL_LABEL         = 'admin.login.email-label',
  LOGIN_EMAIL_PLACEHOLDER   = 'admin.login.email-placeholder',
  LOGIN_PASSWORD_LABEL      = 'admin.login.password-label',
  LOGIN_PASSWORD_PLACEHOLDER = 'admin.login.password-placeholder',
  LOGIN_SUBMIT              = 'admin.login.submit',
  LOGIN_SUBMITTING          = 'admin.login.submitting',
  LOGIN_BACK                = 'admin.login.back',
  LOGIN_ERROR               = 'admin.login.error',

  // ─── Cloudinary Upload ────────────────────────────────────────────────────
  UPLOAD_CHANGE      = 'admin.upload.change',
  UPLOAD_DRAG_TITLE  = 'admin.upload.drag-title',
  UPLOAD_DRAG_SUB    = 'admin.upload.drag-sub',
  UPLOAD_DRAG_HINT   = 'admin.upload.drag-hint',
  UPLOAD_UPLOADING   = 'admin.upload.uploading',
  UPLOAD_MANUAL_URL  = 'admin.upload.manual-url',
  UPLOAD_ERROR       = 'admin.upload.error',


  // ─── Table ────────────────────────────────────────────────────
  TABLE_ACTION      = 'admin.table.actions',
  TABLE_LOADING     = 'admin.table.loading',
  TABLE_EMPTY_DATA  = 'admin.table.empty-data',
  TABLE_ACTION_EDIT = 'admin.table.action.edit',
  TABLE_ACTION_DELETE = 'admin.table.action.delete',
  TABLE_PER_PAGE    = 'admin.table.per-page',
  TABLE_SELECTED    = 'admin.table.selected',
  TABLE_DESELECT    = 'admin.table.deselect',


  // ───Diaglog────────────────────────────────────────────────────
  DIAGLOG_CONFIRM_DELETE_TITLE = "admin.diaglog.delete.confirm-title",
  DIAGLOG_CONFIRM_DELETE_LABEL = "admin.diaglog.delete.confirm-label",
  DIAGLOG_CONFIRM_DELETE_ACTION_DELETE = "admin.diaglog.delete.action.delete",
  DIAGLOG_CONFIRM_DELETE_ACTION_CANCEL = "admin.diaglog.delete.action.cancel",
  DIAGLOG_CONFIRM_DELETE_MESSAGE = "admin.diaglog.delete.message",
}
