export enum ApplicationMessage {
  FILE_NOT_EXITS = "file.not.exists",
  FILE_TYPE_APPLY = "file.type.apply",
  FILE_MAX_SIZE = "file.max.size",
  LOADING_PROCESS = "loading.process",
}

export enum ApplicationTitle {
  CATEGORY              = 'category',
  ARCHIVES              = 'archives',
  HAVE_A_QUESTIONS      = 'have-questions?',
  WRITE_BY              = "write-by",
  CONTINUE_READING      = "continuing-reading",
  NEWS_LETTER_TITLE     = "news-letter.title",
  NEW_LETTER_CONTENT    = "news-letter.content",
  EMAIL_ADDRESS         = "email-address",
  SUBSCRIBE             = "subscribe",
  CONTACT_INFORMATION   = "contact-information",
  ADDRESS               = "address",
  PHONE                 = "phone",
  EMAIL                 = "email",
  WEBSITE               = "website",
  YOUR_NAME             = "your-name",
  YOUR_EMAIL            = "your-email",
  SUBJECT               = "subject",
  MESSAGE               = "message",
  SEND_MESSAGE          = "send-message",
  HELLO_I_AM            = "hello-i-am",
  MORE_ABOUT_ME         = "more-about-me",
  ARTICLES              = "articles",
  ARTICLE_DESCRIPTION   = "articles-description",
  DESCRIPTION_SEARCH_BOX= "description-search-box",
  POPULAR_ARTICLES      = "popular-articles",
  TAG_CLOUD             = "tag-cloud",
  OUR_STORY             = "our-story",
  PHOTO                 = "photo",
  COMMENT               = "comment",
  REPLY                 = "reply",
  LEAVE_COMMENT         = "leave-a-comment",
  POST_COMMENT          = "post-comment",
}

export enum AdminMessage {
  // ─── Shared ──────────────────────────────────────────────────────────────
  SAVE              = 'admin.save',
  SAVING            = 'admin.saving',
  CANCEL            = 'admin.cancel',
  ERROR_GENERIC     = 'admin.error.generic',
  LOADING           = 'admin.loading',
  LABEL_NAME          = 'admin.label.name',
  LABEL_TITLE         = 'admin.label.title',
  LABEL_DESCRIPTION   = 'admin.label.description',
  LABEL_IMAGE         = 'admin.label.image',
  LABEL_ORDER         = 'admin.label.order',
  LABEL_KEY           = 'admin.label.key',
  LABEL_VALUE         = 'admin.label.value',
  LABEL_LANGUAGE      = 'admin.label.language',
  LABEL_SLUG          = 'admin.label.slug',
  LABEL_VIEWS         = 'admin.label.views',
  LABEL_LIKE          = 'admin.label.like',
  LABEL_COMMENT_COUNT = 'admin.label.comment-count',
  LABEL_CREATED_DATE  = 'admin.label.created-date',
  LABEL_IMAGE_COUNT   = 'admin.label.image-count',
  LABEL_ARTICLE_COUNT = 'admin.label.article-count',
  LABEL_CONTENT       = 'admin.label.content',
  LABEL_ARTICLE_ID    = 'admin.label.article-id',
  LABEL_REPLY_ID      = 'admin.label.reply-id',
  LABEL_LANG_CODE     = 'admin.label.lang-code',
  LABEL_USERNAME      = 'admin.label.username',
  LABEL_EMAIL         = 'admin.label.email',
  LABEL_PHONE         = 'admin.label.phone',
  LABEL_BIO           = 'admin.label.bio',

  // ─── Dashboard ───────────────────────────────────────────────────────────
  DASHBOARD_TITLE         = 'admin.dashboard.title',
  DASHBOARD_SUBTITLE      = 'admin.dashboard.subtitle',
  DASHBOARD_QUICK         = 'admin.dashboard.quick',
  DASHBOARD_NEW_ARTICLE   = 'admin.dashboard.new-article',
  DASHBOARD_NEW_ALBUM     = 'admin.dashboard.new-album',
  DASHBOARD_NEW_CATEGORY  = 'admin.dashboard.new-category',
  DASHBOARD_NEW_TAG       = 'admin.dashboard.new-tag',
  DASHBOARD_SETTINGS      = 'admin.dashboard.settings',
  DASHBOARD_STAT_ARTICLES   = 'admin.dashboard.stat.articles',
  DASHBOARD_STAT_ALBUMS     = 'admin.dashboard.stat.albums',
  DASHBOARD_STAT_CATEGORIES = 'admin.dashboard.stat.categories',
  DASHBOARD_STAT_TAGS       = 'admin.dashboard.stat.tags',
  DASHBOARD_STAT_FILES      = 'admin.dashboard.stat.files',
  DASHBOARD_STAT_USERS      = 'admin.dashboard.stat.users',

  // ─── Articles ─────────────────────────────────────────────────────────────
  ARTICLES_PAGE_TITLE    = 'admin.articles.title',
  ARTICLES_CREATE_BTN    = 'admin.articles.create',
  ARTICLES_MODAL_CREATE  = 'admin.articles.modal.create',
  ARTICLES_MODAL_EDIT    = 'admin.articles.modal.edit',
  ARTICLES_FORM_TITLE    = 'admin.articles.form.title',
  ARTICLES_FORM_DESC     = 'admin.articles.form.desc',
  ARTICLES_FORM_CONTENT  = 'admin.articles.form.content',
  ARTICLES_FORM_COVER    = 'admin.articles.form.cover',
  ARTICLES_FORM_CATEGORIES = 'admin.articles.form.categories',
  ARTICLES_FORM_TAGS     = 'admin.articles.form.tags',
  ARTICLES_SAVE          = 'admin.articles.save',

  // ─── Albums ───────────────────────────────────────────────────────────────
  ALBUMS_PAGE_TITLE    = 'admin.albums.title',
  ALBUMS_SUBTITLE      = 'admin.albums.subtitle',
  ALBUMS_CREATE_BTN    = 'admin.albums.create',
  ALBUMS_MODAL_CREATE  = 'admin.albums.modal.create',
  ALBUMS_MODAL_EDIT    = 'admin.albums.modal.edit',
  ALBUMS_FORM_PARENT    = 'admin.albums.form.parent',
  ALBUMS_FORM_NO_PARENT = 'admin.albums.form.no-parent',
  ALBUMS_VIEW_LIST     = 'admin.albums.view.list',
  ALBUMS_VIEW_TREE     = 'admin.albums.view.tree',
  ALBUMS_VIEW_EXPLORER = 'admin.albums.view.explorer',
  ALBUMS_EMPTY_CHILDREN = 'admin.albums.empty-children',
  ALBUMS_FILES_TITLE   = 'admin.albums.files.title',
  ALBUMS_FILES_EMPTY   = 'admin.albums.files.empty',
  ALBUMS_FILES_ADD     = 'admin.albums.files.add',
  ALBUMS_FILES_REMOVE  = 'admin.albums.files.remove',
  ALBUMS_ROOT          = 'admin.albums.root',

  // ─── Tags ─────────────────────────────────────────────────────────────────
  TAGS_PAGE_TITLE   = 'admin.tags.title',
  TAGS_SUBTITLE     = 'admin.tags.subtitle',
  TAGS_CREATE_BTN   = 'admin.tags.create',
  TAGS_MODAL_CREATE = 'admin.tags.modal.create',
  TAGS_MODAL_EDIT   = 'admin.tags.modal.edit',

  // ─── Categories ───────────────────────────────────────────────────────────
  CATEGORIES_PAGE_TITLE   = 'admin.categories.title',
  CATEGORIES_SUBTITLE     = 'admin.categories.subtitle',
  CATEGORIES_CREATE_BTN   = 'admin.categories.create',
  CATEGORIES_MODAL_CREATE = 'admin.categories.modal.create',
  CATEGORIES_MODAL_EDIT   = 'admin.categories.modal.edit',

  // ─── Users ────────────────────────────────────────────────────────────────
  USERS_PAGE_TITLE    = 'admin.users.title',
  USERS_SUBTITLE      = 'admin.users.subtitle',
  USERS_MODAL_EDIT    = 'admin.users.modal.edit',
  USERS_FORM_USERNAME = 'admin.users.form.username',
  USERS_FORM_EMAIL    = 'admin.users.form.email',
  USERS_FORM_PHONE    = 'admin.users.form.phone',
  USERS_FORM_BIO      = 'admin.users.form.bio',

  // ─── Languages ────────────────────────────────────────────────────────────
  LANGUAGES_PAGE_TITLE   = 'admin.languages.title',
  LANGUAGES_SUBTITLE     = 'admin.languages.subtitle',
  LANGUAGES_CREATE_BTN   = 'admin.languages.create',
  LANGUAGES_MODAL_CREATE = 'admin.languages.modal.create',
  LANGUAGES_MODAL_EDIT   = 'admin.languages.modal.edit',
  LANGUAGES_FORM_CODE    = 'admin.languages.form.code',

  // ─── Translations ─────────────────────────────────────────────────────────
  TRANSLATIONS_PAGE_TITLE      = 'admin.translations.title',
  TRANSLATIONS_SUBTITLE        = 'admin.translations.subtitle',
  TRANSLATIONS_ADD_KEY_BTN     = 'admin.translations.add-key',
  TRANSLATIONS_CREATE_BTN      = 'admin.translations.create',
  TRANSLATIONS_MODAL_CREATE    = 'admin.translations.modal.create',
  TRANSLATIONS_MODAL_EDIT      = 'admin.translations.modal.edit',
  TRANSLATIONS_MODAL_KEY_TITLE = 'admin.translations.modal.key-title',
  TRANSLATIONS_FORM_VALUE      = 'admin.translations.form.value',
  TRANSLATIONS_FORM_CHOOSE_KEY  = 'admin.translations.form.choose-key',
  TRANSLATIONS_FORM_CHOOSE_LANG = 'admin.translations.form.choose-lang',
  TRANSLATIONS_SAVE_KEY        = 'admin.translations.save-key',

  // ─── Sys Config ───────────────────────────────────────────────────────────
  SYSCONFIG_PAGE_TITLE       = 'admin.sys-config.title',
  SYSCONFIG_SUBTITLE         = 'admin.sys-config.subtitle',
  SYSCONFIG_CREATE_BTN       = 'admin.sys-config.create',
  SYSCONFIG_MODAL_CREATE     = 'admin.sys-config.modal.create',
  SYSCONFIG_MODAL_EDIT       = 'admin.sys-config.modal.edit',
  SYSCONFIG_FORM_VALUE_LABEL = 'admin.sys-config.form.value-label',
  SYSCONFIG_FORM_HINT        = 'admin.sys-config.form.hint',

  // ─── Files ────────────────────────────────────────────────────────────────
  FILES_PAGE_TITLE      = 'admin.files.title',
  FILES_CREATE_BTN      = 'admin.files.create',
  FILES_MODAL_CREATE    = 'admin.files.modal.create',
  FILES_MODAL_EDIT      = 'admin.files.modal.edit',
  FILES_FORM_MEDIA      = 'admin.files.form.media',
  FILES_EMPTY           = 'admin.files.empty',
  FILES_DROP_HINT       = 'admin.files.drop',
  FILES_BATCH_UPLOADING = 'admin.files.batch',
  FILES_UPLOAD_REQUIRED = 'admin.files.upload-required',
  FILES_SAVE_FAILED     = 'admin.files.save-failed',

  // ─── Sidebar ──────────────────────────────────────────────────────────────
  SIDEBAR_HOME              = 'admin.sidebar.home',
  SIDEBAR_LOGOUT            = 'admin.sidebar.logout',
  SIDEBAR_NAV_DASHBOARD     = 'admin.sidebar.nav.dashboard',
  SIDEBAR_NAV_ARTICLES      = 'admin.sidebar.nav.articles',
  SIDEBAR_NAV_ALBUMS        = 'admin.sidebar.nav.albums',
  SIDEBAR_NAV_CATEGORIES    = 'admin.sidebar.nav.categories',
  SIDEBAR_NAV_TAGS          = 'admin.sidebar.nav.tags',
  SIDEBAR_NAV_COMMENTS      = 'admin.sidebar.nav.comments',
  SIDEBAR_NAV_FILES         = 'admin.sidebar.nav.files',
  SIDEBAR_NAV_USERS         = 'admin.sidebar.nav.users',
  SIDEBAR_NAV_LANGUAGES     = 'admin.sidebar.nav.languages',
  SIDEBAR_NAV_TRANSLATIONS  = 'admin.sidebar.nav.translations',
  SIDEBAR_NAV_SETTINGS      = 'admin.sidebar.nav.settings',

  // ─── Login ────────────────────────────────────────────────────────────────
  LOGIN_TITLE               = 'admin.login.title',
  LOGIN_SUBTITLE            = 'admin.login.subtitle',
  LOGIN_EMAIL_LABEL         = 'admin.login.email-label',
  LOGIN_EMAIL_PLACEHOLDER   = 'admin.login.email-placeholder',
  LOGIN_PASSWORD_LABEL      = 'admin.login.password-label',
  LOGIN_PASSWORD_PLACEHOLDER = 'admin.login.password-placeholder',
  LOGIN_SUBMIT              = 'admin.login.submit',
  LOGIN_SUBMITTING          = 'admin.login.submitting',
  LOGIN_BACK                = 'admin.login.back',
  LOGIN_ERROR               = 'admin.login.error',

  // ─── Cloudinary Upload ────────────────────────────────────────────────────
  UPLOAD_CHANGE      = 'admin.upload.change',
  UPLOAD_DRAG_TITLE  = 'admin.upload.drag-title',
  UPLOAD_DRAG_SUB    = 'admin.upload.drag-sub',
  UPLOAD_DRAG_HINT   = 'admin.upload.drag-hint',
  UPLOAD_UPLOADING   = 'admin.upload.uploading',
  UPLOAD_MANUAL_URL  = 'admin.upload.manual-url',
  UPLOAD_ERROR       = 'admin.upload.error',


  // ─── Table ────────────────────────────────────────────────────
  TABLE_ACTION = "admin.table.actions",
  TABLE_LOADING = "admin.table.loading",
  TABLE_EMPTY_DATA = "admin.table.empty-data",
  TABLE_ACTION_EDIT = "admin.table.action.edit",
  TABLE_ACTION_DELETE = "admin.table.action.delete",


  // ───Diaglog────────────────────────────────────────────────────
  DIAGLOG_CONFIRM_DELETE_TITLE = "admin.diaglog.delete.confirm-title",
  DIAGLOG_CONFIRM_DELETE_LABEL = "admin.diaglog.delete.confirm-label",
  DIAGLOG_CONFIRM_DELETE_ACTION_DELETE = "admin.diaglog.delete.action.delete",
  DIAGLOG_CONFIRM_DELETE_ACTION_CANCEL = "admin.diaglog.delete.action.cancel",
  DIAGLOG_CONFIRM_DELETE_MESSAGE = "admin.diaglog.delete.message",
}
